name = "Sea Fabric"
author = "Sea Jr."
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15df25a451abacd890a16fcc3f90f40231624a0ed5bf59d384f08914d9bd7820"

[versions]
fabric = "0.15.6"
minecraft = "1.20.4"
