name = "Sea Fabric"
author = "Sea Jr."
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87902061e88595ef79490588ad04bf1263431c2d9fc56e11ec2dbd12112d1521"

[versions]
fabric = "0.15.6"
minecraft = "1.20.4"
