name = "Sea Fabric"
author = "Sea Jr."
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d55d44e74c16fbee6dd518288ede151c726e0e7ca25e2758b413a34e3e74075"

[versions]
fabric = "0.15.6"
minecraft = "1.20.4"
